### ISSUE TITLE
allow_broker=True for ConfidentialClientApplication returns error

### ISSUE THREAD

**Issue by victormatyiku** [AzureAD/microsoft-authentication-library-for-python#544]
**Describe the bug**
Trying to pass allow_broker=True for as an argument for ConfidentialClientApplication returns an error that it is not supported. However, the [documentation](https://msal-python.readthedocs.io/en/latest/index.html#msal.ConfidentialClientApplication.params.allow_broker) says that it is supported.

**Expected behavior**
For the package to try to create a broker.

**What you see instead**
Traceback (most recent call last):
  File "c:\Users\matyvic\Documents\CSPC\colectica-rest-api-demo\python\corestica\corestica.py", line 561, in <module>
    staging_test = ColecticaRepository(
  File "c:\Users\matyvic\Documents\CSPC\colectica-rest-api-demo\python\corestica\corestica.py", line 131, in __init__
    self.authenticate_via_sign_in(username, password)
  File "c:\Users\matyvic\Documents\CSPC\colectica-rest-api-demo\python\corestica\corestica.py", line 171, in authenticate_via_sign_in
    app = msal.ConfidentialClientApplication(
  File "C:\Users\matyvic\AppData\Roaming\Python\Python39\site-packages\msal\application.py", line 555, in __init__
    raise ValueError("allow_broker=True is only supported in PublicClientApplication")
ValueError: allow_broker=True is only supported in PublicClientApplication

**The MSAL Python version you are using**
1.21.0

**Comment by rayluo** [comment]
That error `ValueError: allow_broker=True is only supported in PublicClientApplication` is intentional and self-explained. It is our docs that currently reuse the same inline content from the base class. We will see what we can do to improve the doc.

Meanwhile, please do not use `allow_broker=True` in your `ConfidentialClientApplication`.
